### ISSUE TITLE
AsyncEventPublisherInterface doesn't have $storeId property

### ISSUE THREAD

**Issue by Swahjak** [mage-os/mageos-async-events#31]
I was confused as to how the store filtering worked since I could not seem to find a property for setting it, but it seems that the `AsyncEventPublisherInterface` (which I assume is the correct class for DI) doesn't have the `storeId` property while `AsyncEventPublisher` does.

**Comment by Swahjak** [comment]
Also it seems like in https://github.com/mage-os/mageos-async-events/pull/26/files the type of the property was changed to `string`, which seems inconsistent / wrong. I'm not sure why it was necessary but if typing is applied it should be `int`, shouldn't it?

**Comment by gowrizrh** [comment]
Hi @Swahjak, it looks like it was missed on the interface and should be present there. thanks for picking this up :slightly_smiling_face: 

regarding the string instead of int, this will have to be a string simply because we define everything we publish to a topic is a string. please see https://github.com/mage-os/mageos-async-events/blob/4.x/etc/communication.xml#L4

as to why it's changed recently to a string, please see https://github.com/mage-os/mageos-async-events/pull/26#issuecomment-2194237079

**Comment by Swahjak** [comment]
I see your argument, but isn't that exposing / enforcing logic required by the publisher to the client? Wouldn't it make sense to i.e. make sure conversion happens in the publisher? A simple `(string)` cast on https://github.com/mage-os/mageos-async-events/blob/4.x/Model/AsyncEventPublisher.php#L37 would do?

Awaiting you comment before updating the pull (including the feat/ branch name)

**Comment by gowrizrh** [comment]
true, the current approach is a bit of a poor design choice. my main concern was introducing a breaking change with this. however, if you can make that change and update the PR and all tests pass, we can package it up in a beta release and see how it goes.

**Comment by Swahjak** [comment]
I've made the adjustment and opened a new merge request with the `feature/` branch name.
